changelog:
  categories:
    - title: Features
      labels: [ 'enhancement', 'feature' ]
    - title: Fixes
      labels: [ 'bug', 'fix' ]
    - title: Dependencies
      labels: [ 'dependencies' ]
    - title: Other changes
      labels: [ '*' ]
  exclude:
    labels: [ 'skip-changelog' ]