[versions]
spring = "6.2.19"
junit = "5.14.4"
assertj = "3.27.7"
mockito = "5.24.0"
maven = "3.9.16"
mavenPluginTools = "3.15.2"
mavenPluginDevelopment = "1.0.3"
jspecify = "1.0.0"

[libraries]
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.14.4" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version = "1.14.4" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
maven-plugin-api = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven" }
maven-plugin-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "mavenPluginTools" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
maven-plugin-development = { id = "org.gradlex.maven-plugin-development", version.ref = "mavenPluginDevelopment" }